[book]
authors = ["Haolin"]
language = "zh-cn"
multilingual = false
src = "src"
title = "Cpp Notes"
description = "真·从零开始的C++笔记"

[build]
build-dir = "docs"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = false
additional-css = ["css/chinese-patch.css"]
mathjax-support = true
copy-fonts = true
git-repository-url = "https://github.com/attr0/Cpp-Notes"
git-repository-icon = "fa-github"

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
copyable = false
copy-js = false
line-numbers = true
runnable = false