[book]
authors = ["haolin"]
language = "zh-cn"
multilingual = false
src = "src"
title = "Cpp Notes"
description = "真·从零开始的C++笔记"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
git-repository-url = "https://github.com/attr0/Cpp-Notes"
git-repository-icon = "fa-github"